//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlToJSONConverterWebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FactEvent()
        {
            this.Qualifiers = new HashSet<Qualifier>();
        }
    
        public long FactID { get; set; }
        public long opta_event_id { get; set; }
        public long fixture_id { get; set; }
        public Nullable<short> away_score { get; set; }
        public Nullable<short> home_score { get; set; }
        public string period { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string timestamp_milliseconds { get; set; }
        public Nullable<short> period_id { get; set; }
        public Nullable<byte> period_minute { get; set; }
        public Nullable<byte> period_second { get; set; }
        public Nullable<long> player_id { get; set; }
        public Nullable<short> event_id { get; set; }
        public Nullable<short> event_type_id { get; set; }
        public string event_type_name { get; set; }
        public long team_id { get; set; }
        public Nullable<short> outcome { get; set; }
        public string game_status { get; set; }
        public Nullable<byte> timer_running { get; set; }
        public string direction { get; set; }
        public Nullable<decimal> direction_of_play_x { get; set; }
        public Nullable<decimal> direction_of_play_y { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public Nullable<int> related_event_id { get; set; }
        public string gameAdditional { get; set; }
        public string eventAdditional { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qualifier> Qualifiers { get; set; }
    }
}
