//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlToJSONConverterWebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualifier
    {
        public long ID { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public Nullable<long> qualifier_id { get; set; }
        public Nullable<long> event_id { get; set; }
        public string qualifierAdditional { get; set; }
    
        public virtual FactEvent FactEvent { get; set; }
    }
}
